### PR TITLE
Clean up the JDBC feature

### PR DESCRIPTION
**Pull request by Mailaender**
Followup of https://github.com/OpenChrom/openchrom3rdpl/commit/1492089c250ebe3ec98e830195d1944b56d07186 as every mentioned plugin except the Oracle DB one already got its own feature.

### CODE REVIEW

**Comment by eselmeister** [comment]
Instead of renaming the jdbc feature, please create a distinct Oracle JDBC feature. The jdbc feature can be used as a kind of collector feature for various jdbc related libraries. As far as I understand, the Oracle JDBC feature allows to detect a local connector *.jar file to access Oracle databases, am I right?

**Comment by Mailaender** [comment]
I just kept the Oracle JDBC plugin because https://github.com/OpenChrom/openchrom3rdpl/tree/develop/openchrom/plugins/net.openchrom.thirdpartylibraries.oracle did exist. It, however, seems to bundle nothing just like the rest.

**Comment by Mailaender** [comment]
https://github.com/OpenChrom/openchrom3rdpl/commit/c1962d4212303fbb27ce61fbbd63c1dff0b2e19a actually says it: due to licensing issues it can't be bundled. Now I understand the fuzz.

**Comment by eselmeister** [comment]
The feature:
`net.openchrom.thirdpartylibraries.jdbc.feature`

has been renamed to:
`net.openchrom.thirdpartylibraries.oracle.feature`

Please keep the JDBC feature and add a distinct, new Oracle connector feature.

**Comment by Mailaender** [comment]
I also rebased it onto https://github.com/OpenChrom/openchrom3rdpl/pull/15 and added the sqlite feature.

**Pull request merged**
